### ISSUE TITLE
Error when initializing GUI, no data is displayed

### ISSUE THREAD

**Issue by amelieziller** [translationalneurosurgery/tool-offspect#21]
When trying to initialize the gui for my hdf5 file, I get the following error stating "Exception 0 not in cachefile" and the gui opens but I cannot see any data:

![error3](https://user-images.githubusercontent.com/63000628/78361742-2d70fb00-75b9-11ea-8006-af2922878e01.JPG)

![error2](https://user-images.githubusercontent.com/63000628/78361660-0b777880-75b9-11ea-8ce1-b9ed6e994985.JPG)

**Comment by agricolab** [comment]
The likely cause is that there are no traces in your CacheFile, likely due to an error during creation, e.g. there was no localite stream. Try `offspect peek edclz.hdf5`, to check. If there is no output, the file is empty. Otherwise you would expect sth. like:
```
-------------------------------------------------------------------------------
origin               : template_R001.xdf
filedate             : 1970-01-01 00:01:01
subject              : VnNn
samplingrate         : 1000
samples_pre_event    : 100
samples_post_event   : 100
channel_labels       : ['EDC_L']
readout              : contralateral_mep
global_comment       : patient was tired
history              : 
version              : 0.0.1
traces_count         : 2
```

**Comment by agricolab** [comment]
It is probably best to implement that the GUI give a sensible error message if the file is empty, i.e.
- [ ] check during file loading whether the file is empty
- [ ] raise informative error message

**Comment by amelieziller** [comment]
okay thank you so the problem is with creating the cachefile? I tried creating several cache files of different xdf files of my data and it always leads to a traces_count of 0 
![image](https://user-images.githubusercontent.com/63000628/78363544-3b744b00-75bc-11ea-9009-ce9d39dca98d.png)

**Comment by agricolab** [comment]
Yes, this is likely because currently, for xdf-files, stream and event are hard-coded. Julian is implementing a more flexible approach in https://github.com/translationalneurosurgery/tool-offspect/issues/13, see also https://github.com/translationalneurosurgery/tool-offspect/issues/19. I ask for patience, i expect this to finished next week. It is quite a step as it needs more readouts, multiple channels, and a design of a GUI for this readout.

**Comment by amelieziller** [comment]
okay thank you

**Comment by agricolab** [comment]
Please give the newest version for cachefile creation a try, whether it solves your issue. Please note that now, the tool will not create a file if no events were found and print an abort message instead. Therefore, no need for the GUI to check whether a file contains no traces.

**Comment by amelieziller** [comment]
I tried the newest version and this is what I got when trying liesl, I also tried different files: 
![errorliesl2](https://user-images.githubusercontent.com/63000628/79435735-4ffb0f00-7fd0-11ea-9a1d-ba976493e759.JPG)
![errorliesl3](https://user-images.githubusercontent.com/63000628/79435739-512c3c00-7fd0-11ea-8f92-312f81aca97d.JPG)
![errorliesl1](https://user-images.githubusercontent.com/63000628/79435740-51c4d280-7fd0-11ea-98ea-6571573cb205.JPG)

**Comment by agricolab** [comment]
There is one issue with your xdf-file, as it appears to have recorded the Respiration and BrainVision streams twice. This might have been caused my a mispecified lsl_api.cfg or a bug in liesl on windows, which has been fixed in the meantime. Be as it may, there seem to be no events in the BrainVision RDA Markers stream. Therefore, if you cut for "S  2", there are no events marked "S  2", hence no traces.

**Comment by agricolab** [comment]
As a general remark, please consider to start using fenced codeblocks instead of screenshots https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by agricolab** [comment]
Closing this, because the feature is no longer a requirement per meeting from 24.04.20
