### ISSUE TITLE
ImportError: cannot import name 'pyeep' from 'libeep'

### ISSUE THREAD

**Issue by ethanrich** [translationalneurosurgery/tool-offspect#23]
**Describe the bug**
Pyeep is a shared object file in the libeep root folder and does not load in Python 3.7.6 or 3.5. 

**To Reproduce**
Run `offspect gui -f merged.hdf5` from command prompt in offspect root or run `import libeep` in Python

**Expected behavior**
Open offspect gui

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by agricolab** [comment]
What is the error message when you `import pyeep` with the python working directory in the folder where pyeep.so is located?

I can't compile for windows easily, because i use Linux. But you can try to compile pyeep yourself by following the instructions i layed out here: https://github.com/translationalneurosurgery/tool-libeep

**Comment by ethanrich** [comment]
> What is the error message when you import pyeep with the python working directory in the folder where pyeep.so is located?

`ModuleNotFoundError: No module named 'pyeep'`


`pip install libeep==0.2` resulted in successful CacheFile-making and loading new and old GUI.
