### ISSUE TITLE
Creating cache file was not possible using .xdf data for single electrode (e.g., C3)

### ISSUE THREAD

**Issue by HUtangge** [translationalneurosurgery/tool-offspect#24]
**Describe the bug**
I try to run "offspect tms -f IMONAS-acute-study-intervention_R001.xdf -t intervention_R001.hdf5 -pp 100 100 -r erp -c C3" in the terminal, but it tells me an error. 

<img width="573" alt="Untitled" src="https://user-images.githubusercontent.com/40338535/79138765-5b262300-7db5-11ea-8b9f-55649807f8a7.png">

I also tried in the spyder to use function prepare_annotations (https://github.com/translationalneurosurgery/tool-offspect/blob/f5996a542acb58ebf473f9e193729c86ad6780e1/offspect/input/tms/erp/xdf.py#L37), I changed some codes to make it work,

https://github.com/translationalneurosurgery/tool-offspect/blob/f5996a542acb58ebf473f9e193729c86ad6780e1/offspect/protocols/xdf.py#L90

after line 90, I had one more line 
``` yield trigger_time ```

**Desktop (please complete the following information):**
 - macOS

**Comment by agricolab** [comment]
Dear @HUtangge , the error message clearly describes that the stream `C3` was not found in the data. This is because currently, when you define `erp` as a readout, all channels from a single stream are being selected. I though i made this clear in the instructions i sent around, sorry if they were confusing. The solution is to specify a stream name for `-c`. 
From the instructions:
> -c Instead of a single channel (e.g. EDC_L) we give it the name of a stream, e.e.g "BrainVision RDA". This will collect all channels within this stream and put them in the CacheFile.
-r to inform the tool that we want the whole stream, we set the readout to "erp"

The other issue you mentioned should be behaviour as expected, and please do not proceed with your manipulated code. The `trigger_time` is only valid, if the amplitude was not 0 and the coil position was readable. Therefore, we yield conditioned on that: https://github.com/translationalneurosurgery/tool-offspect/blob/f5996a542acb58ebf473f9e193729c86ad6780e1/offspect/protocols/xdf.py#L91-L95  If you still feel there is a bug, please raise a new issue.
