### ISSUE TITLE
Feature: Expanded time window for MEP peaks - cmep algorithm

### ISSUE THREAD

**Issue by BettinaTrunk** [translationalneurosurgery/tool-offspect#36]
**Is your feature request related to a problem? Please describe.**
Currently, the cmep algorithm searches for MEPs between 15-45ms after TMS onset and both peaks of the MEP have to be in this window. Since latencies for stroke patients could be delayed, it could be reasonable to expand the time window.

**Describe the solution you'd like**
I suggest a time-window between 15-65ms after TMS-onset.

**Comment by agricolab** [comment]
Choose the window to be 15-100ms due to some very late MEPs in test datasets. Additionally, added the option to use the amplitude directly from some manual latency entries. Closed with https://github.com/translationalneurosurgery/tool-offspect/commit/7a61c6d29ce92f6a1e588d6e5830fb56f8dcc257 and https://github.com/translationalneurosurgery/tool-offspect/commit/0d116870644b19849c23198c07ce434c26d4beeb
