### ISSUE TITLE
Bug: Error when trying to plot map from certain cache files

### ISSUE THREAD

**Issue by FelixQuirm** [translationalneurosurgery/tool-offspect#40]
**Describe the bug**
When trying to plot a map from visually inspected cache files, the error shown belows occurs for some (but not all) files. Consistent for single files, yet for one session, one file can be affected while the other may not show the error.

**To Reproduce**
1. Download example files 
2. Set as fname
3. Try to plot via:
`cf = CacheFile(fname)`
`display - plot_map(cf)`

**Expected behavior**
A visual MEP map should be created.

**Screenshots**
![Plotting_Error](https://user-images.githubusercontent.com/42035995/85392166-734fb680-b54b-11ea-99e8-c7b8d2f4af97.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Offspect version: Up to date (0.1.2, f3835e8)

**Comment by agricolab** [comment]
The error stems from all values at all voxels of the image being zero. This was only partially caused by some of the coordinates being outside of the scope. Instead, i stumbled on another, more troublesome bug. 

Every "xyz_coords" is being projected to a specific voxel.If multiple coordinates project on the same voxel, they value is being overwritten. That means, by chance, if the last value of the five repetitions for a target was zero, it would be zero. This bug was therefore exhibited because some coordinates were outside of the plot, and for the remaining targets, the last measurement was 0. Therefore, the maximal value of the the whole image was zero, and there was no colorbar. 

What is worse though, is that instead of averaging, the values were being overwritten. And worst, even for distant targets, it could happen that they were projected to a single voxel. This error is therefore also occuring silently in all other previous plots. Even when the coordinates were sampled, instead of fixed. 

I solved this issue by avering repeated measurements within the same voxel, see https://github.com/translationalneurosurgery/tool-offspect/blob/develop/offspect/cache/plot.py#L40 in acb0b4ab68562ac5f77e30b5baae9d166ccc068e.

Anyone should replot any already plotted maps to account for this issue.
